### ISSUE TITLE
EfgsKeyStore throws java.io.IOException: Stream Closed

### ISSUE THREAD

**Issue by ebeigarts** [eu-federation-gateway-service/efgs-federation-gateway#177]
EfgsKeyStore#getStream function returns closed stream due try-with-resources block that auto-closes the stream.

```java
  private InputStream getStream(String path) {
    try (InputStream fileStream = new FileInputStream(path)) {
      return fileStream;
    } catch (IOException e) {
      log.info("Could not find Keystore {}", path);
    }
    return null;
  }
```

It should probably be:

```java
  private InputStream getStream(String path) {
    try {
      InputStream fileStream = new FileInputStream(path);
      return fileStream;
    } catch (IOException e) {
      log.info("Could not find Keystore {}", path);
    }
    return null;
  }
```

Backtrace:

```
... 91 common frames omitted, Caused by: java.io.IOException: Stream Closed, 
at java.base/java.io.FileInputStream.available0(Native Method), 
at java.base/java.io.FileInputStream.available(Unknown Source), 
at eu.interop.federationgateway.config.EfgsKeyStore.loadKeyStore(EfgsKeyStore.java:72), 
at eu.interop.federationgateway.config.EfgsKeyStore.trustAnchorKeyStore(EfgsKeyStore.java:33), 
at eu.interop.federationgateway.config.EfgsKeyStore$$EnhancerBySpringCGLIB$$3d51035c.CGLIB$trustAnchorKeyStore$0(<generated>), 
at eu.interop.federationgateway.config.EfgsKeyStore$$EnhancerBySpringCGLIB$$3d51035c$$FastClassBySpringCGLIB$$76df2318.invoke(<generated>), 
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244), 
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331), 
at eu.interop.federationgateway.config.EfgsKeyStore$$EnhancerBySpringCGLIB$$3d51035c.trustAnchorKeyStore(<generated>), 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), 
at java.base/java.lang.reflect.Method.invoke(Unknown Source), 
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154), 
... 92 common frames omitted,
```

**Comment by daniel-eder** [comment]
Hi @ebeigarts, thanks for the detailed report. May I ask you to provide a pull request for our Devs to review?
Thank you!

**Comment by ebeigarts** [comment]
@daniel-eder sorry, dont have time for a pr 😟
